from .fast_bottom_fit_overlay import (
    NODE_CLASS_MAPPINGS as OVERLAY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as OVERLAY_NODE_DISPLAY_NAME_MAPPINGS,
)
from .fast_gift_postfx import (
    NODE_CLASS_MAPPINGS as POSTFX_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as POSTFX_NODE_DISPLAY_NAME_MAPPINGS,
)
from .time_remap_speed_presets import (
    NODE_CLASS_MAPPINGS as TIMEREMAP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TIMEREMAP_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(OVERLAY_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(POSTFX_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TIMEREMAP_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(OVERLAY_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(POSTFX_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TIMEREMAP_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
